version: '3.7'
services:
  alfresco-migrator-share:
    image: alfresco-share-alfresco-migrator:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../alfresco-migrator-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: alfresco-migrator-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
    networks:
      - default

  alfresco-migrator-acs:
    image: alfresco-content-services-alfresco-migrator:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../alfresco-migrator-platform-docker/target
    environment:
      JAVA_TOOL_OPTIONS: "${keystore.settings}"
      JAVA_OPTS: "
        -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
        "
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - alfresco-migrator-acs-volume:/usr/local/tomcat/alf_data
      - alfresco-migrator-acs-log-volume:/usr/local/tomcat/logs
    depends_on:
      - alfresco-migrator-postgres
    networks:
      - default

  alfresco-migrator-ass:
    image: alfresco/alfresco-search-services:2.0.3
    environment:
      SOLR_ALFRESCO_HOST: alfresco-migrator-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: alfresco-migrator-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      # HTTPS or SECRET
      ALFRESCO_SECURE_COMMS: "secret"
      # SHARED SECRET VALUE
      JAVA_TOOL_OPTIONS:
          -Dalfresco.secureComms.secret=secret
    ports:
      - "8983:8983"
    volumes:
      - alfresco-migrator-ass-volume:/opt/alfresco-search-services/contentstore
      - alfresco-migrator-ass-volume:/opt/alfresco-search-services/data
    networks:
      - default

volumes:
  alfresco-migrator-acs-volume:
    external: true
  alfresco-migrator-acs-log-volume:
    external: true
  alfresco-migrator-ass-volume:
    external: true

networks:
  default:
    name: active_default
